/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SchoolsTenantIdRouteImport } from './routes/schools.$tenantId'
import { Route as SchoolsTenantIdMaterialsRouteImport } from './routes/schools.$tenantId.materials'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SchoolsTenantIdRoute = SchoolsTenantIdRouteImport.update({
  id: '/schools/$tenantId',
  path: '/schools/$tenantId',
  getParentRoute: () => rootRouteImport,
} as any)
const SchoolsTenantIdMaterialsRoute =
  SchoolsTenantIdMaterialsRouteImport.update({
    id: '/materials',
    path: '/materials',
    getParentRoute: () => SchoolsTenantIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/schools/$tenantId': typeof SchoolsTenantIdRouteWithChildren
  '/schools/$tenantId/materials': typeof SchoolsTenantIdMaterialsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/schools/$tenantId': typeof SchoolsTenantIdRouteWithChildren
  '/schools/$tenantId/materials': typeof SchoolsTenantIdMaterialsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/schools/$tenantId': typeof SchoolsTenantIdRouteWithChildren
  '/schools/$tenantId/materials': typeof SchoolsTenantIdMaterialsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/sign-in' | '/schools/$tenantId' | '/schools/$tenantId/materials'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sign-in' | '/schools/$tenantId' | '/schools/$tenantId/materials'
  id:
    | '__root__'
    | '/'
    | '/sign-in'
    | '/schools/$tenantId'
    | '/schools/$tenantId/materials'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SignInRoute: typeof SignInRoute
  SchoolsTenantIdRoute: typeof SchoolsTenantIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schools/$tenantId': {
      id: '/schools/$tenantId'
      path: '/schools/$tenantId'
      fullPath: '/schools/$tenantId'
      preLoaderRoute: typeof SchoolsTenantIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schools/$tenantId/materials': {
      id: '/schools/$tenantId/materials'
      path: '/materials'
      fullPath: '/schools/$tenantId/materials'
      preLoaderRoute: typeof SchoolsTenantIdMaterialsRouteImport
      parentRoute: typeof SchoolsTenantIdRoute
    }
  }
}

interface SchoolsTenantIdRouteChildren {
  SchoolsTenantIdMaterialsRoute: typeof SchoolsTenantIdMaterialsRoute
}

const SchoolsTenantIdRouteChildren: SchoolsTenantIdRouteChildren = {
  SchoolsTenantIdMaterialsRoute: SchoolsTenantIdMaterialsRoute,
}

const SchoolsTenantIdRouteWithChildren = SchoolsTenantIdRoute._addFileChildren(
  SchoolsTenantIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SignInRoute: SignInRoute,
  SchoolsTenantIdRoute: SchoolsTenantIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
